name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ca66c7c008616b9e0ce3e7e71e6ac7af6cde19f56838ddc7934f3589777758"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
