name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "852f32b2c4eeade821f26aab9376ef610399e99790b48fcb5082ce4983dac3d3"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
