name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72e7edd5f0d59f0dfb43333d847d0d8f9c6deab8cf46ffa450cc4a7684463b4"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
