name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6e9d0ef4c43acdf1638f091e3165506d4b84c7e0557527587416f34f54140af"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
