name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a9905ce480e5a4546cbf08e2333eafe9ecd61b93cf322b011861bdac3a20b41"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
