name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d45755814058c004cb46653657d5644dc046d68f728f1676a6d4b05048d5a31b"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
