name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18a9a5f03df9da017f9da4891f46e8b8921f43adafb01903ed001d0eb28b88be"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
