name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc35f98cef2ea18b4aaf1abf46c2997c0f53e5da746f75c73937c80a47ed4d15"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
