name = "Country of Aurora"
author = "Country of Aurora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44e874161c2697575698b46551a6f868280089f615fde726c655f50235a4bbef"

[versions]
fabric = "0.15.10"
minecraft = "1.19.2"
